### PR TITLE
Adding script to check that all applications work

### LINKED ISSUE #170: Application CHIMaD_benchmark6a fails in version 2.1.2
A segmentation fault: 11 error occurs while solving for the first time step. 

The code seems to work if we switch to branch v 2.1

### PR DESCRIPTION
**Pull request by landinjm**
This script compiles and runs each application in debug mode for 1 timestep to make sure all applications are working prior to a version release.  Each application is run on a separate task, so it can get through most of the applications fairly quickly (except for memory heavy apps like the `CHAC_performance_test`. That said, it might be too hefty for incorporation into the CI. We could incorporate tests for compilation though. 

Summary
----------
- A few files were deleted that seem to leftover from a while ago (batch submission scripts & `integratedFields.txt`).
- The AMR update flags were not properly initialized leading to SEGFAULTS in applications with AMR parameters.
- `CHiMaD_benchmark1a`'s default parameter file does not work as you need to specify 0 outputs when using a list output (#155).  Setting the default values for outputs and restart points to 0 fixes this (see below for discussion on this). 

"Broken" Applications
--------------------
- ~~`steadyStateAllenCahn` Unclear implementation & residual values extremely high~~ Deleting application
- `CHiMaD_benchmark6b` Issues with mismatched manifolds between cells and faces. Not sure how to fix this because it seems to work as intended as some cells with the spherical manifold have bordering faces with the flat manifold cells. Either way it would cause an issue. I think we should just ignore this one for the debug tests. See as there is no adaptive refinement, I've also added the a transfinite interpolation manifold to make the mesh look a bit better [deal.II step-65](https://www.dealii.org/current/doxygen/deal.II/step_65.html). 

Fixed Applications
------------------
- `mechanics` ~~Issue with convergence of linear solve due to instabilities.~~ This way due to commit b0f8edb0d0a43c43058c4bb4d1438a3d4ea85ab9, which naively passed the units tests. This may be due to the fact that the precipitate evolution uses Dirichlet =  0 on all boundaries, unlike the mechanics applications where it is sometimes 0 and sometimes 1. We should revisit our test suite to make sure cases like these area covered.

Closes #170

### CODE REVIEW

**Comment by landinjm** [comment]
We should solve #155 by automatically setting the output files to 0 if we have a `LIST` type. This way, the user can switch between `EQUAL_SPACING` and `LIST` simply by changing the type and adding a list. This would make the quick fixes above obsolete. 

At the same time, I think the default values should be 0 unless the user specifies they want outputs or restarts.

**Comment by landinjm** [comment]
@stvdwtt Do you know what the `steadyStateAllenCahn` application is trying to do? I don't really understand what the psi field is trying to do.

**Comment by stvdwtt** [comment]
@landinjm, the idea was to fast-forward to the steady state of a Cahn-Hilliard-Allen-Cahn system of equations, where the Cahn-Hilliard equation is replaced with a mass-conserving Allen-Cahn equation (essentially, any mass that is lost in a time step is added uniformly across the domain, this facilitates non-local evolution and gets to _a_ steady state more quickly than Cahn-Hilliard).

We used it in this NanoHub application:
https://nanohub.org/resources/prismspfmisfit/supportingdocs?sitenotice=close&sitenotice=close

If all you're planning to do is calculate the equilibrium shape of a precipitate, then this kind of approach should be faster than normal time stepping. Of course the intermediate steps are entirely fictitious so it tells you nothing about the evolution.

**Comment by landinjm** [comment]
Ok, thanks!

**Comment by landinjm** [comment]
> We should solve #155 by automatically setting the output files to 0 if we have a `LIST` type. This way, the user can switch between `EQUAL_SPACING` and `LIST` simply by changing the type and adding a list. This would make the quick fixes above obsolete.
> 
> At the same time, I think the default values should be 0 unless the user specifies they want outputs or restarts.

This is fixed by changing the logic in how we set the output list. See commit a3d2d36d6f61461b3eb23b098cabbb62d1a6c188.

**Pull request merged**
