### PR TITLE
Output checkpoint paths

### PR DESCRIPTION
**Pull request by kkarayagiz**

### CODE REVIEW

**Comment by stvdwtt** [comment]
Is this just waiting on unit tests? Is the code itself ready to go?

**Comment by kkarayagiz** [comment]
I think so.

**Comment by david-montiel-t** [comment]
Sorry, I was supposed to work on the unit tests but I just haven't had
time.

I will try to get them done  the today or over the weekend.

David

**Comment by david-montiel-t** [comment]
Merging 6 commits into prisms-center:output-checkpoint_paths from kkarayagiz:output-checkpoint_paths

**Pull request merged**
